In [1]:
import torch

In [2]:
x = torch.tensor([[1.,2,3],[4,5,6],[7,8,9]]).unsqueeze(0) # unsqueeze is for BS at dim=0
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [3]:
len=3
i_coord = torch.linspace(start=1/len, end=1, steps=len).view(len, -1).expand(-1, len)
j_coord = torch.linspace(start=1/len, end=1, steps=len).view(1, len).expand(len, -1)
coords  = torch.stack([i_coord, j_coord])
coords.shape, coords

(torch.Size([2, 3, 3]),
 tensor([[[0.3333, 0.3333, 0.3333],
          [0.6667, 0.6667, 0.6667],
          [1.0000, 1.0000, 1.0000]],
 
         [[0.3333, 0.6667, 1.0000],
          [0.3333, 0.6667, 1.0000],
          [0.3333, 0.6667, 1.0000]]]))

In [4]:
torch.cat((x, coords), dim=0)

tensor([[[1.0000, 2.0000, 3.0000],
         [4.0000, 5.0000, 6.0000],
         [7.0000, 8.0000, 9.0000]],

        [[0.3333, 0.3333, 0.3333],
         [0.6667, 0.6667, 0.6667],
         [1.0000, 1.0000, 1.0000]],

        [[0.3333, 0.6667, 1.0000],
         [0.3333, 0.6667, 1.0000],
         [0.3333, 0.6667, 1.0000]]])

In [5]:
coords.expand(2,-1,-1,-1)

tensor([[[[0.3333, 0.3333, 0.3333],
          [0.6667, 0.6667, 0.6667],
          [1.0000, 1.0000, 1.0000]],

         [[0.3333, 0.6667, 1.0000],
          [0.3333, 0.6667, 1.0000],
          [0.3333, 0.6667, 1.0000]]],


        [[[0.3333, 0.3333, 0.3333],
          [0.6667, 0.6667, 0.6667],
          [1.0000, 1.0000, 1.0000]],

         [[0.3333, 0.6667, 1.0000],
          [0.3333, 0.6667, 1.0000],
          [0.3333, 0.6667, 1.0000]]]])

In [6]:
x.shape

torch.Size([1, 3, 3])

In [7]:
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [11]:
x = torch.randn(3, 2, 3, 3) # BS, C, X, Y
x

tensor([[[[ 0.3132, -1.2751,  0.3140],
          [-0.8071,  1.0047, -0.0824],
          [-1.1597,  0.2384,  0.6021]],

         [[-0.1609,  0.1951, -0.9957],
          [-0.0579, -1.4935, -0.8635],
          [-0.3646, -0.7525,  0.1695]]],


        [[[-1.0702, -0.7219, -1.1978],
          [ 0.7428,  0.8093, -0.7165],
          [ 2.1106, -0.0861, -2.2430]],

         [[-0.8242, -1.3410,  0.3254],
          [ 2.3096,  0.9264, -0.8569],
          [-0.3412, -0.0806,  1.2696]]],


        [[[-1.5374,  1.2101,  0.2651],
          [ 0.6887,  2.6190,  0.9181],
          [ 0.3885,  0.9141,  1.0118]],

         [[ 0.0968,  0.7336, -0.9341],
          [-0.6265,  3.0547,  2.2440],
          [ 1.2600, -0.7724,  0.6212]]]])

In [12]:
class AddCoord2D(torch.nn.Module):
    def __init__(self, len):
        super(AddCoord2D, self).__init__()
        
        i_coord = torch.linspace(start=1/len, end=1, steps=len).view(len, -1).expand(-1, len)
        j_coord = torch.linspace(start=1/len, end=1, steps=len).view(-1, len).expand(len, -1)
        self.coords = torch.stack([i_coord, j_coord])

        print(self.coords.shape)

    def forward(self, x): # X shape: [BS, C, X, Y]
        BS = x.shape[0]
        return torch.cat((x, self.coords.expand(BS,-1,-1,-1)), dim=1)


In [13]:
addcoord = AddCoord2D(3)
addcoord(x)

torch.Size([2, 3, 3])


tensor([[[[ 0.3132, -1.2751,  0.3140],
          [-0.8071,  1.0047, -0.0824],
          [-1.1597,  0.2384,  0.6021]],

         [[-0.1609,  0.1951, -0.9957],
          [-0.0579, -1.4935, -0.8635],
          [-0.3646, -0.7525,  0.1695]],

         [[ 0.3333,  0.3333,  0.3333],
          [ 0.6667,  0.6667,  0.6667],
          [ 1.0000,  1.0000,  1.0000]],

         [[ 0.3333,  0.6667,  1.0000],
          [ 0.3333,  0.6667,  1.0000],
          [ 0.3333,  0.6667,  1.0000]]],


        [[[-1.0702, -0.7219, -1.1978],
          [ 0.7428,  0.8093, -0.7165],
          [ 2.1106, -0.0861, -2.2430]],

         [[-0.8242, -1.3410,  0.3254],
          [ 2.3096,  0.9264, -0.8569],
          [-0.3412, -0.0806,  1.2696]],

         [[ 0.3333,  0.3333,  0.3333],
          [ 0.6667,  0.6667,  0.6667],
          [ 1.0000,  1.0000,  1.0000]],

         [[ 0.3333,  0.6667,  1.0000],
          [ 0.3333,  0.6667,  1.0000],
          [ 0.3333,  0.6667,  1.0000]]],


        [[[-1.5374,  1.2101,  0.2651],
     